MovieRama/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('movies.urls')),
]

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', include("django.contrib.auth.urls")),
    path('register/', views.register, name="register"),
]

movies/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.MoviesView.as_view(), name="movie_list"),
    path('order_by=<order>', views.MoviesView.as_view(), name="sort_movies"),
    path('<int:user_id>/', views.UserMoviesView.as_view(), name="user_movies"),
    path('<int:user_id>/order_by=<order>', views.UserMoviesView.as_view(), name="sort_user_movies"),
    path('react/', views.react_to_movie, name="react_to_movie"),
    path('add/', views.add_movie, name="add_movie"),

]

accounts/models.py
from django.contrib.auth.models import User


# Create your models here.
def get_name(self):
    """
        Returns a string based on :model:`auth.User` first name and last name
    """
    return '{} {}'.format(self.first_name, self.last_name)


User.add_to_class("__str__", get_name)

movies/models.py
from django.conf import settings
from django.db import models


# Create your models here.

class Movie(models.Model):
    """
        Stores a single movie, related to :model:`auth.User`.
    """
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=1000)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, )
    pub_date = models.DateTimeField('date published')
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_likes", blank=True)
    hates = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_hates", blank=True)

    def __str__(self):
        """
            Returns a movie by its title
        """
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    """
        A sign up form requiring all :model:`auth.User` info fields
    """
    first_name = forms.CharField(max_length=100, help_text='Required')
    last_name = forms.CharField(max_length=100, help_text='Required')
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect

from .forms import SignupForm


def register(request):
    """
        Display a registration form for a :model:`auth.User`.

        **Context**

        ``form``
            An instance of SignupForm

        **Template:**

            :template:`registration/register.html`
    """
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            login(request, user)
            return redirect("/")
    else:
        form = SignupForm()
    return render(request, 'registration/register.html', {'form': form})

movies/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from .models import Movie


class MoviesView(generic.ListView):
    """
        Displays the list of movies

        **Context**

            ``movies``
                The list of movies

        **Template:**

            :template:`movies/index.html`
    """
    model = Movie
    template_name = "movies/index.html"
    context_object_name = "movies"

    def get_ordering(self):
        """
            Displays the list of movies based on the defined argument
        """
        if 'order' in self.kwargs:
            if self.kwargs['order'] == 'pub_date':
                ordering = "-" + self.kwargs['order']
            else:
                ordering = self.kwargs['order']
            return ordering
        else:
            return '-pub_date'


class UserMoviesView(MoviesView):
    """
        Displays the list of the user's movies

        **Context**

            ``movies``
                The list of user's movies

        **Template:**

            :template:`movies/index.html`
    """

    def get_queryset(self):
        """
            Returns the movies posted by the user with the specified user_id
        """
        queryset = super(MoviesView, self).get_queryset()
        queryset = queryset.filter(user_id=self.kwargs['user_id'])
        return queryset

    def get_context_data(self, **kwargs):
        """
            Passes the user_id to the context to be usable in the template
        """
        context = super(MoviesView, self).get_context_data(**kwargs)
        context['user_id'] = self.kwargs['user_id']
        return context


@login_required(login_url='/accounts/login/')
def react_to_movie(request):
    """
        Updates the list of likes or hates of the movie based on the user's selection.
        The user should be logged in order to be able to react to a movie.
    """
    if request.method == "POST":
        movie_id = request.POST.get('movie_id')
        movie = Movie.objects.get(pk=movie_id)
        if movie.user != request.user:
            if 'like_btn' in request.POST:
                if request.user in movie.likes.all():
                    movie.likes.remove(request.user)
                else:
                    movie.likes.add(request.user)
                    movie.hates.remove(request.user)
            elif 'hate_btn' in request.POST:
                if request.user in movie.hates.all():
                    movie.hates.remove(request.user)
                else:
                    movie.hates.add(request.user)
                    movie.likes.remove(request.user)
            return HttpResponseRedirect(reverse('movies:movie_list'))
    return HttpResponse(status=204)


@login_required(login_url='/accounts/login/')
def add_movie(request):
    """
        Display a form to create a new :model:`movies.Movie`.

        **Template:**

            :template:`movies/add.html`
    """
    if request.method == "POST":
        movie_title = request.POST.get('title')
        movie_desc = request.POST.get('desc')
        movie = Movie(title=movie_title, desc=movie_desc, pub_date=datetime.now(), user=request.user)
        movie.save()
        return HttpResponseRedirect(reverse('movies:movie_list'))
    return render(request, 'movies/add.html')

movies/templates/movies/add.html
{% extends 'home.html' %}

{% block title %}Add Movie{% endblock %}

{% block content %}

    <div class="row mt-4">
        <div class="col">
            <form action="{% url 'movies:add_movie' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        <label class="form-label">Movie name </label>
                        <input class="form-control" type="text" name="title">
                    </div>
                    <div class="col-12">
                        <label class="form-label">Movie description </label>
                        <textarea class="form-control" name="desc"></textarea>
                    </div>
                    <div class="col-12 my-4 text-center">
                        <button class="btn btn-primary" type="submit">Add Movie</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'home.html' %}

{% block content %}

    <!--------------------------------Navbar for movie ordering--------------------------------->

    <nav class="nav my-4 border border-dark p-1">
        <span class="navbar-text">Order by:</span>
        {% if user_id %}
            <a class="nav-link" href="{% url 'movies:sort_user_movies' user_id 'pub_date' %}">date</a>
            <div class="vr"></div>
            <a class="nav-link" href="{% url 'movies:sort_user_movies' user_id 'likes' %}">like</a>
            <div class="vr"></div>
            <a class="nav-link" href="{% url 'movies:sort_user_movies' user_id 'hates' %}">hate</a>
        {% else %}
            <a class="nav-link" href="{% url 'movies:sort_movies' 'pub_date' %}">date</a>
            <div class="vr"></div>
            <a class="nav-link" href="{% url 'movies:sort_movies' 'likes' %}">like</a>
            <div class="vr"></div>
            <a class="nav-link" href="{% url 'movies:sort_movies' 'hates' %}">hate</a>
        {% endif %}
    </nav>
    <!--------------------------------End navbar--------------------------------->

    <!--------------------------------Movies list--------------------------------->

    <div class="row">
        <div class="col">
            {% for movie in movies %}
                <!--------------------------------Movie details--------------------------------->
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ movie.title }}</h5>
                        <p class="card-substitle">
                            Posted by
                            {% if movie.user == user %}
                                <a href="{% url 'movies:user_movies' movie.user.id %}">You</a>
                            {% else %}
                                <a href="{% url 'movies:user_movies' movie.user.id %}">{{ movie.user }}</a>
                            {% endif %}
                            {{ movie.pub_date | timesince }} ago
                        </p>
                        <p class="card-text">{{ movie.desc }}</p>

                        <!--------------------------------Movie like/hate variations--------------------------------->

                        <div class="row">
                            <div class="col-auto">
                                <form action="{% url 'movies:react_to_movie' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="movie_id" value="{{ movie.id }}">
                                    {% if user == movie.user or user in movie.likes.all %}
                                        <button class="btn btn-link" name="like_btn"
                                                type="submit" disabled>{{ movie.likes.count }} Likes
                                        </button>
                                    {% else %}
                                        <button class="btn btn-link" name="like_btn"
                                                type="submit">{{ movie.likes.count }} Likes
                                        </button>
                                    {% endif %}
                                    {% if user == movie.user or user in movie.hates.all %}
                                        <button class="btn btn-link" name="hate_btn"
                                                type="submit" disabled>{{ movie.hates.count }} Hates
                                        </button>
                                    {% else %}
                                        <button class="btn btn-link" name="hate_btn"
                                                type="submit">{{ movie.hates.count }} Hates
                                        </button>
                                    {% endif %}
                                </form>
                            </div>
                            {% if user in movie.likes.all or user in movie.hates.all %}
                                <div class="col text-end">
                                    <form action="{% url 'movies:react_to_movie' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="movie_id" value="{{ movie.id }}">
                                        <div class="row justify-content-end align-items-center">
                                            <div class="col-auto">
                                                <div class="hstack gap-3">
                                                    {% if user in movie.likes.all %}
                                                        <div> You like this movie</div>
                                                        <div class="vr"></div>
                                                        <button class="btn btn-link" name="like_btn"
                                                                type="submit">Unlike
                                                        </button>
                                                    {% elif user in movie.hates.all %}
                                                        <div> You hate this movie</div>
                                                        <div class="vr"></div>
                                                        <button class="btn btn-link" name="hate_btn"
                                                                type="submit">Unhate
                                                        </button>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            {% endif %}
                        </div>
                        <!--------------------------------End movie like/hate variations------------------------------>
                    </div>
                </div>
                <!--------------------------------End movie details--------------------------------->
            {% endfor %}
        </div>
        <!--------------------------------End movies list--------------------------------->

        <!--------------------------------Add new movie--------------------------------->
        {% if user.is_authenticated %}
            <div class="col-auto">
                <a class="btn btn-success" href="{% url 'movies:add_movie' %}">Add Movie</a>
            </div>
        {% endif %}
    </div>

    <!--------------------------------End add new movie--------------------------------->
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>{% block title %}MovieRama{% endblock %}</title>
</head>
<body>
{% block header %}
{% endblock %}
<div class="container">

{% block content %}
{% endblock %}
</div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block header %}
    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">MovieRama</a>
            <div class="navbar-nav text-light align-items-center">
                {% if user.is_authenticated %}
                    Hi {{ user }}
                    <a class="mx-3" href="{% url 'accounts:logout' %}">Log Out</a>
                {% else %}
                    <a class="mx-3" href="{% url 'accounts:login' %}">Log In</a>
                    or
                    <a class="mx-3 btn btn-primary" href="{% url 'accounts:register' %}">Register</a>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
{% endblock %}